// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef TZH_h
#define TZH_h
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
enum DIRECTION {RIGHT, LEFT, UP, DOWN}; 

class SoundBox : public Fl_Box {
public:
  SoundBox(int x, int y, int w, int h);
  int handle(int e);
};
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *quit_confirm;
#include <FL/Fl_Box.H>
extern Fl_Box *QuitBackground;
#include <FL/Fl_Button.H>
extern Fl_Button *yes;
extern Fl_Button *no;
extern Fl_Double_Window *scorewin;
#include <FL/Fl_Output.H>
extern Fl_Output *scoreout;
extern Fl_Double_Window *window;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *GameOver;
extern Fl_Box *death;
extern Fl_Box *gameoverbackground;
extern Fl_Box *background;
extern Fl_Button *start;
extern Fl_Button *quit;
extern Fl_Box *map;
extern Fl_Box *zombie_right;
extern Fl_Box *zombie_left;
extern Fl_Box *zombie_up;
extern Fl_Box *zombie_down;
extern Fl_Box *Ham;
extern Fl_Box *player;
extern Fl_Box *bullet_right;
extern Fl_Box *bullet_left;
extern Fl_Box *bullet_up;
extern Fl_Box *bullet_down;
extern SoundBox *music;
extern Fl_Button *replay;
extern Fl_Button *credit_button;
extern Fl_Box *title;
extern Fl_Box *instructions;
extern Fl_Button *instr_button;
extern Fl_Box *Credits;
extern Fl_Button *menu_button;
extern Fl_Button *x2loud4u;
extern Fl_Box *speedupbox;
extern Fl_Box *snoopbox;
void back_to_menu(void*);
void display_credits(void*);
void credits_animation(void*);
void select(void*);
void cb_move_right(void *);
void cb_move_up(void *);
void cb_move_down(void *);
void cb_move_left(void *);
void logo_animation(void*);
void logo_load();
void logo_fadeout(void*);
void mainmenu_load(void*);
void item_delay(void*);
void display_instr(void*);
bool collision(int dir, int cor);
void player_facing(DIRECTION d);
void set_gamescreen(int startcheck, int replaycheck);
void bullet_move_right(void *);
void bullet_move_up(void *);
void bullet_move_down(void *);
void bullet_move_left(void *);
void right_zombie_death_animation(void*);
void left_zombie_death_animation(void*);
void up_zombie_death_animation(void*);
void down_zombie_death_animation(void*);
bool bullet_collision(int dir);
void zombie_death(int dir, double& counter);
void adjust_difficulty(int counternum,int& movingspeed);
void show_speedupmsg(void*);
void bullet_reset(int dir);
void gunfire(int orient);
void player_death(void*);
void top_death_anim_reversal(void*);
void top_death_load();
void top_death_animation(void*);
void top_death_fadeout(void*);
void call_gameover(void*);
void snoop_animation(void*);
#endif
